//Todos los comentarios de este archivo estan generadas por la IA Copilot

// Importa los tipos de metadatos de Next.js para definir información como el título y la descripción de la página.
import type { Metadata } from "next";

// Importa las fuentes Geist y Geist_Mono desde Google Fonts utilizando el paquete de Next.js.
import { Geist, Geist_Mono } from "next/font/google";

// Importa los estilos globales definidos en el archivo globals.css.
import "./globals.css";

// Configuración de la fuente Geist Sans con una variable CSS personalizada y el subconjunto "latin".
const geistSans = Geist({
  variable: "--font-geist-sans", // Define una variable CSS para usar esta fuente en el proyecto.
  subsets: ["latin"], // Especifica el subconjunto de caracteres que se utilizarán.
});

// Configuración de la fuente Geist Mono con una variable CSS personalizada y el subconjunto "latin".
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Define una variable CSS para usar esta fuente en el proyecto.
  subsets: ["latin"], // Especifica el subconjunto de caracteres que se utilizarán.
});

// Define los metadatos de la aplicación, como el título y la descripción.
export const metadata: Metadata = {
  title: "Create Next App", // Título de la aplicación.
  description: "Generated by create next app", // Descripción de la aplicación.
};

// Componente RootLayout que envuelve toda la aplicación.
export default function RootLayout({
  children, // Recibe los elementos hijos que se renderizarán dentro del layout.
}: Readonly<{
  children: React.ReactNode; // Define el tipo de los elementos hijos como React.ReactNode.
}>) {
  return (
    // Define el idioma del documento HTML como inglés.
    <html lang="en">
      <body
        // Aplica las clases CSS para las fuentes Geist Sans y Geist Mono, junto con la clase antialiased para suavizar el texto.
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Renderiza los elementos hijos dentro del cuerpo del documento. */}
        {children}
      </body>
    </html>
  );
}
